### ISSUE TITLE
Color contrast/accessibility issue for warning popups (white text on yellow bg)

### ISSUE THREAD

**Issue by neoncitylights** [NathanBrodin/zed-vercel-theme#1]
Hi! Found this while looking through the Zed extensions, thank you for the lovely theme :)

For reference, I am using Zed 0.157.5 (`6192aa14692a24f279888e0b5f781ce204bda57b`).

There seems to be an accessibility issue for warning popups when there's a yellow squiggly line. When you hover over the squiggly line, a yellow bg popup shows up with white text on it. Maybe this could be changed to black text instead.

<img width="1822" alt="image" src="https://github.com/user-attachments/assets/f35fa547-4e4a-47c5-bcb5-4c394cd569cf">

Also, I'm not sure why, but it says the theme strings aren't valid in settings.json (collapsed it since it's long):
<details>
<summary>Error message</summary>

> Value is not accepted. Valid values: "Andromeda", "Atelier Cave Dark", "Atelier Cave Light", "Atelier Dune Dark", "Atelier Dune Light", "Atelier Estuary Dark", "Atelier Estuary Light", "Atelier Forest Dark", "Atelier Forest Light", "Atelier Heath Dark", "Atelier Heath Light", "Atelier Lakeside Dark", "Atelier Lakeside Light", "Atelier Plateau Dark", "Atelier Plateau Light", "Atelier Savanna Dark", "Atelier Savanna Light", "Atelier Seaside Dark", "Atelier Seaside Light", "Atelier Sulphurpool Dark", "Atelier Sulphurpool Light", "Ayu Dark", "Ayu Light", "Ayu Mirage", "Base16 3024", "Base16 Apathy", "Base16 Apprentice", "Base16 Ashes", "Base16 Atelier Cave", "Base16 Atelier Cave Light", "Base16 Atelier Dune", "Base16 Atelier Dune Light", "Base16 Atelier Estuary", "Base16 Atelier Estuary Light", "Base16 Atelier Forest", "Base16 Atelier Forest Light", "Base16 Atelier Heath", "Base16 Atelier Heath Light", "Base16 Atelier Lakeside", "Base16 Atelier Lakeside Light", "Base16 Atelier Plateau", "Base16 Atelier Plateau Light", "Base16 Atelier Savanna", "Base16 Atelier Savanna Light", "Base16 Atelier Seaside", "Base16 Atelier Seaside Light", "Base16 Atelier Sulphurpool", "Base16 Atelier Sulphurpool Light", "Base16 Atlas", "Base16 Ayu Dark", "Base16 Ayu Light", "Base16 Ayu Mirage", "Base16 Bespin", "Base16 Black Metal", "Base16 Black Metal (Bathory) Dark", "Base16 Black Metal (Burzum)", "Base16 Black Metal (Dark Funeral)", "Base16 Black Metal (Gorgoroth)", "Base16 Black Metal (Immortal)", "Base16 Black Metal (Khold)", "Base16 Black Metal (Marduk)", "Base16 Black Metal (Mayhem)", "Base16 Black Metal (Nile)", "Base16 Black Metal (Venom)", "Base16 Blue Forest", "Base16 Blueish", "Base16 Brewer", "Base16 Bright", "Base16 Brogrammer", "Base16 Brush Trees", "Base16 Brush Trees Dark", "Base16 Catppuccin Frappe", "Base16 Catppuccin Latte", "Base16 Catppuccin Macchiato", "Base16 Catppuccin Mocha", "Base16 Chalk", "Base16 Circus", "Base16 Classic Dark", "Base16 Classic Light", "Base16 Codeschool", "Base16 Colors", "Base16 Cupcake", "Base16 Cupertino", "Base16 Da One Black", "Base16 Da One Gray", "Base16 Da One Ocean", "Base16 Da One Paper", "Base16 Da One Sea", "Base16 Da One White", "Base16 DanQing", "Base16 DanQing Light", "Base16 Darcula", "Base16 Dark Violet", "Base16 Darktooth", "Base16 Decaf", "Base16 Default Dark", "Base16 Default Light", "Base16 Dracula", "Base16 Edge Dark", "Base16 Edge Light", "Base16 Eighties", "Base16 Embers", "Base16 Equilibrium Dark", "Base16 Equilibrium Gray Dark", "Base16 Equilibrium Gray Light", "Base16 Equilibrium Light", "Base16 Espresso", "Base16 Eva", "Base16 Eva Dim", "Base16 Evenok Dark", "Base16 Everforest", "Base16 Everforest Dark Hard", "Base16 Flat", "Base16 Framer", "Base16 Fruit Soda", "Base16 Gigavolt", "Base16 Github", "Base16 Google Dark", "Base16 Google Light", "Base16 Gotham", "Base16 Grayscale Dark", "Base16 Grayscale Light", "Base16 Green Screen", "Base16 Gruber", "Base16 Gruvbox Material Dark, Hard", "Base16 Gruvbox Material Dark, Medium", "Base16 Gruvbox Material Dark, Soft", "Base16 Gruvbox Material Light, Hard", "Base16 Gruvbox Material Light, Medium", "Base16 Gruvbox Material Light, Soft", "Base16 Gruvbox dark, hard", "Base16 Gruvbox dark, medium", "Base16 Gruvbox dark, pale", "Base16 Gruvbox dark, soft", "Base16 Gruvbox light, hard", "Base16 Gruvbox light, medium", "Base16 Gruvbox light, soft", "Base16 Hardcore", "Base16 Harmonic16 Dark", "Base16 Harmonic16 Light", "Base16 Heetch Dark", "Base16 Heetch Light", "Base16 Helios", "Base16 Hopscotch", "Base16 Horizon Dark", "Base16 Horizon Light", "Base16 Horizon Terminal Dark", "Base16 Horizon Terminal Light", "Base16 Humanoid dark", "Base16 Humanoid light", "Base16 IR Black", "Base16 Icy Dark", "Base16 Isotope", "Base16 Kanagawa", "Base16 Katy", "Base16 Kimber", "Base16 London Tube", "Base16 Macintosh", "Base16 Marrakesh", "Base16 Materia", "Base16 Material", "Base16 Material Darker", "Base16 Material Lighter", "Base16 Material Palenight", "Base16 Material Vivid", "Base16 Mellow Purple", "Base16 Mexico Light", "Base16 Mocha", "Base16 Monokai", "Base16 Mountain", "Base16 Nebula", "Base16 Nord", "Base16 Nova", "Base16 Ocean", "Base16 OceanicNext", "Base16 One Light", "Base16 OneDark", "Base16 Outrun Dark", "Base16 Oxocarbon Dark", "Base16 Oxocarbon Light", "Base16 PaperColor Dark", "Base16 PaperColor Light", "Base16 Paraiso", "Base16 Pasque", "Base16 PhD", "Base16 Pico", "Base16 Pop", "Base16 Porple", "Base16 Primer Dark", "Base16 Primer Dark Dimmed", "Base16 Primer Light", "Base16 Purpledream", "Base16 Qualia", "Base16 Railscasts", "Base16 Rebecca", "Base16 Rosé Pine", "Base16 Rosé Pine Dawn", "Base16 Rosé Pine Moon", "Base16 Sagelight", "Base16 Sakura", "Base16 Sandcastle", "Base16 Seti UI", "Base16 ShadeSmear Dark", "Base16 ShadeSmear Light", "Base16 Shades of Purple", "Base16 Shapeshifter", "Base16 Silk Dark", "Base16 Silk Light", "Base16 Snazzy", "Base16 Solar Flare", "Base16 Solar Flare Light", "Base16 Solarized Dark", "Base16 Solarized Light", "Base16 Spaceduck", "Base16 Spacemacs", "Base16 Stella", "Base16 Still Alive", "Base16 Summerfruit Dark", "Base16 Summerfruit Light", "Base16 Synth Midnight Terminal Dark", "Base16 Synth Midnight Terminal Light", "Base16 Tango", "Base16 Tokyo City Dark", "Base16 Tokyo City Light", "Base16 Tokyo City Terminal Dark", "Base16 Tokyo City Terminal Light", "Base16 Tokyo Night Dark", "Base16 Tokyo Night Light", "Base16 Tokyo Night Storm", "Base16 Tokyo Night Terminal Dark", "Base16 Tokyo Night Terminal Light", "Base16 Tokyo Night Terminal Storm", "Base16 Tokyodark", "Base16 Tokyodark Terminal", "Base16 Tomorrow", "Base16 Tomorrow Night", "Base16 Tomorrow Night Eighties", "Base16 Twilight", "Base16 Unikitty Dark", "Base16 Unikitty Light", "Base16 Unikitty Reversible", "Base16 UwUnicorn", "Base16 Windows 10", "Base16 Windows 10 Light", "Base16 Windows 95", "Base16 Windows 95 Light", "Base16 Windows High Contrast", "Base16 Windows High Contrast Light", "Base16 Windows NT", "Base16 Windows NT Light", "Base16 Woodland", "Base16 XCode Dusk", "Base16 Zenbones", "Base16 Zenburn", "Base16 caroline", "Base16 darkmoss", "Base16 dirtysea", "Base16 emil", "Base16 eris", "Base16 iA Dark", "Base16 iA Light", "Base16 lime", "Base16 pandora", "Base16 pinky", "Base16 selenized-black", "Base16 selenized-dark", "Base16 selenized-light", "Base16 selenized-white", "Base16 standardized-dark", "Base16 standardized-light", "Base16 summercamp", "Base16 tarot", "Base16 tender", "Base16 vice", "Base16 vulcan", "Catppuccin Frappé", "Catppuccin Frappé - No Italics", "Catppuccin Latte", "Catppuccin Latte - No Italics", "Catppuccin Macchiato", "Catppuccin Macchiato - No Italics", "Catppuccin Mocha", "Catppuccin Mocha - No Italics", "Github Dark", "Github Dark Colorblind", "Github Dark Dimmed", "Github Dark High Contrast", "Github Dark Tritanopia", "Github Light", "Github Light Colorblind", "Github Light High Contrast", "Github Light Tritanopia", "Gruvbox Dark", "Gruvbox Dark Hard", "Gruvbox Dark Soft", "Gruvbox Light", "Gruvbox Light Hard", "Gruvbox Light Soft", "One Dark", "One Light", "Rosé Pine", "Rosé Pine Dawn", "Rosé Pine Moon", "Sandcastle", "Solarized Dark", "Solarized Light", "Summercamp", "Xcode Bare", "Xcode Basic", "Xcode Classic Dark", "Xcode Classic Light", "Xcode Default Dark", "Xcode Default Light", "Xcode High Contrast Dark", "Xcode High Contrast Light", "Xcode Low Key", "Xcode Midnight", "Xcode Presentation Dark", "Xcode Presentation Light", "Xcode Spartan", "Xcode Sunset", "macOS Classic Dark", "macOS Classic Dark2", "macOS Classic Light".

</details>

**Comment by neoncitylights** [comment]
Ack sorry, I think this might not be related with the extension itself. Fwiw, this happened after I was switching from a different theme (Catapuccin Latte iirc); I believe this is an issue with Zed itself instead for loading a theme for the first time.

I ended up restarting the editor and I'm not seeing this issue anymore. I'm seeing the proper warning colors now (red bg with white text). Thank you again anyways :) Great theme!

**Comment by NathanBrodin** [comment]
Hi! Thank you for trying out my theme, and for taking the time to report the issue! 
Yes, Zed can indeed be a bit buggy at times. I'm glad everything is working fine for you now. Let me know if you run into any other issues!
