### ISSUE TITLE
Time for a new release

### ISSUE THREAD

**Issue by chungweileong94** [NathanBrodin/zed-vercel-theme#6]
Been using the latest theme from main branch for about a month now, and I haven't notice any color contrast issue. So I guess it's time for a new release😉

**Comment by NathanBrodin** [comment]
Hey, sorry I forgot to push the update on Zed’s repo 😅 It’s Christmas so I can’t do it right now but I’ll do it on the 26!

**Comment by chungweileong94** [comment]
No worries👍

**Comment by NathanBrodin** [comment]
The pull request has been made, now we have to wait for them to merge it! (only takes a few days max)

**Comment by chungweileong94** [comment]
Appreciated!
