### ISSUE TITLE
bug: selected text in error modal is not visible

### ISSUE THREAD

**Issue by aayushchugh** [NathanBrodin/zed-vercel-theme#7]
If you select some text in error popup, it's not visible

![image](https://github.com/user-attachments/assets/5e3b1a55-a995-42e4-86e2-0869ecdca3e7)

**Comment by chungweileong94** [comment]
Yeah, this is the last issue that I noticed. It's not just the error popup, but any popup with text highlighted.
I’ve been trying to figure out how to change the color but failed at the end. It would be good if someone can show me some clue.😅
